### ISSUE TITLE
Wrong file identifier/HTTP URL specified

### ISSUE THREAD

**Issue by yauhenisayko** [mymmrac/telego#207]
### 💬 Telego version

v0.29.1

### 👾 Issue description

Hello! For some reason, when sending a media group, I get the following error: telego: sendMediaGroup(): api: 400 "Bad Request: failed to send message #1 with the error message "Wrong file identifier/HTTP URL specified"". However, if I send the same files one by one, everything works fine. First, I get the file using the method tu.FileFromURL(messageFile.Url), then I pass the list of these files to tu.MediaGroup(), and after that, I call the SendMediaGroup method, which results in the error. Could you please advise what might be the problem?

**Comment by mymmrac** [comment]
Hello, this error (`Wrong file identifier/HTTP URL specified`) occurs when a URL is not valid in some sort, I already had same issues before for literally no reason, sometime Telegram caches URL files with bad file inside, try adding to URL any query parameter in order to change it (for example `https://example.com/image.png` => `https://example.com/image.png?123` ), this might help. Also make sure file is served correctly (it has proper HTTP Content-Type header).

If nothing helps, please provide code example, I will try to look at it.
